name: common_utils
description: Dart common utils library.Contain DateUtil, EncryptUtil, JsonUtil, LogUtil, MoneyUtil, NumUtil, ObjectUtil, RegexUtil, TextUtil, TimelineUtil, TimerUtil.
version: 0.0.1
homepage: https://github.com/hazedays/common_utils

environment:
  sdk: ^3.5.4

dependencies:
  # https://pub.dev/packages/rational
  rational: ^2.2.3
  # https://pub.dev/packages/decimal
  decimal: ^3.2.1
  # https://pub.dev/packages/crypto
  crypto: ^3.0.6
  # https://pub.dev/packages/convert
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0